[package]
name = "hctl-model-checker"
version = "0.1.0"
authors = ["Ondrej Huvar <ohuvar@gmail.com>"]
edition = "2021"

#[profile.release]
#lto = true

[profile.test]
opt-level = 3

[[bin]]
name = "experiment"
path = "src/bin/experiment.rs"

[[bin]]
name = "inference"
path = "src/bin/infer_networks.rs"

[[bin]]
name = "print-regulations"
path = "src/bin/print_regulations.rs"


[dependencies]
biodivine-lib-bdd = "0.3.0"
biodivine-lib-param-bn = { git = "https://github.com/sybila/biodivine-lib-param-bn.git", branch = "hctl-experimental" }
biodivine-aeon-server = { git = "https://github.com/sybila/biodivine-aeon-server", branch = "hctl-experimental" }
termcolor = "1.1.2"
rand = "0.6.5"

